version: "@project.version@"

app:
  message: "This is the primary Application Property for ${spring.application.name}"

server:
  port: 8080
  address: 0.0.0.0

spring:
  profiles:
    active: dev
  application:
    name: Profiles

api:
  client:
    server:
      cliente:
        path:
          listall: "/clientes"
          byid: "/clientes"
          save: "/clientes"
          update: "/clientes"
          delete: "/clientes/desativar"
      pedido:
        path:
          listall: "/pedidos"
          byNumber: "/pedidos"
          save: "/pedidos/checkout"
          update: "/pedidos/status"
      produto:
        path:
          listall: "/produtos"
          byid: "/produtos"
          save: "/produtos"
          upade: "/produtos"
          delete: "/produtos"
      pagamento:
        path:
          byNumber: "/pagamentos"
          history: "/historico"
