apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-gateway
  labels:
    app: tech-challenge-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-gateway
  template:
    metadata:
      labels:
        app: tech-challenge-gateway
    spec:
      containers:
        - name: tech-challenge-gateway
          image: gleniomontovani/tech-challenge-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: URL_CLIENT_SERVER
              value: http://${URL_CLIENT}:8081/v1
            - name: COGNITO
              value: ${URL_COGNITO}                            
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
                        