apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-gateway-service
  labels:
    app: tech-challenge-gateway
spec:
  selector:
    app: tech-challenge-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer